"""empty message

Revision ID: 0c0f933773aa
Revises: a4d7a99248bd
Create Date: 2022-09-15 12:21:12.590668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0f933773aa'
down_revision = 'a4d7a99248bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_pic', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_pic')
    # ### end Alembic commands ###
