"""empty message

Revision ID: a4d7a99248bd
Revises: db0c9b534871
Create Date: 2022-09-12 16:02:39.493658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d7a99248bd'
down_revision = 'db0c9b534871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_pic', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    # ### end Alembic commands ###
